name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      - run: npm install
      - run: gulp build
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'elmah-blog-ghost-theme-b5.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Push .zip to Ghost Pro
        uses: TryGhost/action-deploy-theme@v1.3.1
        with:
          api-url: ${{ secrets.GHOST_PRO_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_PRO_ADMIN_API_KEY }}
          file: elmah-blog-ghost-theme.zip
      - name: Upload .zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: elmah-blog-ghost-theme-b5.zip
          path: elmah-blog-ghost-theme-b5.zip
